[plugin]
repository = "https://github.com/Helios747/AdaptiveHudPlugin.git"
commit = "78a15021fdb9a4ace5e2d75ecea259b2e4e3e20f"
owners = [
    "Helios747"
]
project_path = "AdaptiveHud"
changelog = "Fixes cases where the config window gets stuck too small"
